// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd_acc2d.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cmd_acc2d.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ignition {
namespace msgs {

namespace {

const ::google::protobuf::Descriptor* CmdAcc2D_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CmdAcc2D_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_cmd_5facc2d_2eproto() {
  protobuf_AddDesc_cmd_5facc2d_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "cmd_acc2d.proto");
  GOOGLE_CHECK(file != NULL);
  CmdAcc2D_descriptor_ = file->message_type(0);
  static const int CmdAcc2D_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CmdAcc2D, header_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CmdAcc2D, acceleration_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CmdAcc2D, theta_),
  };
  CmdAcc2D_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CmdAcc2D_descriptor_,
      CmdAcc2D::default_instance_,
      CmdAcc2D_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CmdAcc2D, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CmdAcc2D, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CmdAcc2D));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_cmd_5facc2d_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CmdAcc2D_descriptor_, &CmdAcc2D::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_cmd_5facc2d_2eproto() {
  delete CmdAcc2D::default_instance_;
  delete CmdAcc2D_reflection_;
}

void protobuf_AddDesc_cmd_5facc2d_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::ignition::msgs::protobuf_AddDesc_ignition_2fmsgs_2fheader_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017cmd_acc2d.proto\022\rignition.msgs\032\032igniti"
    "on/msgs/header.proto\"\\\n\010CmdAcc2D\022%\n\006head"
    "er\030\001 \001(\0132\025.ignition.msgs.Header\022\027\n\014accel"
    "eration\030\002 \001(\001:\0010\022\020\n\005theta\030\003 \001(\001:\0010B#\n\021co"
    "m.ignition.msgsB\016CmdAcc2DProtos", 191);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cmd_acc2d.proto", &protobuf_RegisterTypes);
  CmdAcc2D::default_instance_ = new CmdAcc2D();
  CmdAcc2D::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_cmd_5facc2d_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_cmd_5facc2d_2eproto {
  StaticDescriptorInitializer_cmd_5facc2d_2eproto() {
    protobuf_AddDesc_cmd_5facc2d_2eproto();
  }
} static_descriptor_initializer_cmd_5facc2d_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CmdAcc2D::kHeaderFieldNumber;
const int CmdAcc2D::kAccelerationFieldNumber;
const int CmdAcc2D::kThetaFieldNumber;
#endif  // !_MSC_VER

CmdAcc2D::CmdAcc2D()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ignition.msgs.CmdAcc2D)
}

void CmdAcc2D::InitAsDefaultInstance() {
  header_ = const_cast< ::ignition::msgs::Header*>(&::ignition::msgs::Header::default_instance());
}

CmdAcc2D::CmdAcc2D(const CmdAcc2D& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ignition.msgs.CmdAcc2D)
}

void CmdAcc2D::SharedCtor() {
  _cached_size_ = 0;
  header_ = NULL;
  acceleration_ = 0;
  theta_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CmdAcc2D::~CmdAcc2D() {
  // @@protoc_insertion_point(destructor:ignition.msgs.CmdAcc2D)
  SharedDtor();
}

void CmdAcc2D::SharedDtor() {
  if (this != default_instance_) {
    delete header_;
  }
}

void CmdAcc2D::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CmdAcc2D::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CmdAcc2D_descriptor_;
}

const CmdAcc2D& CmdAcc2D::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cmd_5facc2d_2eproto();
  return *default_instance_;
}

CmdAcc2D* CmdAcc2D::default_instance_ = NULL;

CmdAcc2D* CmdAcc2D::New() const {
  return new CmdAcc2D;
}

void CmdAcc2D::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<CmdAcc2D*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 7) {
    ZR_(acceleration_, theta_);
    if (has_header()) {
      if (header_ != NULL) header_->::ignition::msgs::Header::Clear();
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CmdAcc2D::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ignition.msgs.CmdAcc2D)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .ignition.msgs.Header header = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_acceleration;
        break;
      }

      // optional double acceleration = 2 [default = 0];
      case 2: {
        if (tag == 17) {
         parse_acceleration:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &acceleration_)));
          set_has_acceleration();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_theta;
        break;
      }

      // optional double theta = 3 [default = 0];
      case 3: {
        if (tag == 25) {
         parse_theta:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &theta_)));
          set_has_theta();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ignition.msgs.CmdAcc2D)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ignition.msgs.CmdAcc2D)
  return false;
#undef DO_
}

void CmdAcc2D::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ignition.msgs.CmdAcc2D)
  // optional .ignition.msgs.Header header = 1;
  if (has_header()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->header(), output);
  }

  // optional double acceleration = 2 [default = 0];
  if (has_acceleration()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->acceleration(), output);
  }

  // optional double theta = 3 [default = 0];
  if (has_theta()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->theta(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ignition.msgs.CmdAcc2D)
}

::google::protobuf::uint8* CmdAcc2D::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ignition.msgs.CmdAcc2D)
  // optional .ignition.msgs.Header header = 1;
  if (has_header()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->header(), target);
  }

  // optional double acceleration = 2 [default = 0];
  if (has_acceleration()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->acceleration(), target);
  }

  // optional double theta = 3 [default = 0];
  if (has_theta()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->theta(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ignition.msgs.CmdAcc2D)
  return target;
}

int CmdAcc2D::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .ignition.msgs.Header header = 1;
    if (has_header()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->header());
    }

    // optional double acceleration = 2 [default = 0];
    if (has_acceleration()) {
      total_size += 1 + 8;
    }

    // optional double theta = 3 [default = 0];
    if (has_theta()) {
      total_size += 1 + 8;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CmdAcc2D::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CmdAcc2D* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CmdAcc2D*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CmdAcc2D::MergeFrom(const CmdAcc2D& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_header()) {
      mutable_header()->::ignition::msgs::Header::MergeFrom(from.header());
    }
    if (from.has_acceleration()) {
      set_acceleration(from.acceleration());
    }
    if (from.has_theta()) {
      set_theta(from.theta());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CmdAcc2D::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CmdAcc2D::CopyFrom(const CmdAcc2D& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CmdAcc2D::IsInitialized() const {

  return true;
}

void CmdAcc2D::Swap(CmdAcc2D* other) {
  if (other != this) {
    std::swap(header_, other->header_);
    std::swap(acceleration_, other->acceleration_);
    std::swap(theta_, other->theta_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CmdAcc2D::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CmdAcc2D_descriptor_;
  metadata.reflection = CmdAcc2D_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

// @@protoc_insertion_point(global_scope)
