// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple_car_state.proto

#ifndef PROTOBUF_simple_5fcar_5fstate_2eproto__INCLUDED
#define PROTOBUF_simple_5fcar_5fstate_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/header.pb.h"
#include "ignition/msgs/time.pb.h"
// @@protoc_insertion_point(includes)

namespace ignition {
namespace msgs {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_simple_5fcar_5fstate_2eproto();
void protobuf_AssignDesc_simple_5fcar_5fstate_2eproto();
void protobuf_ShutdownFile_simple_5fcar_5fstate_2eproto();

class SimpleCarState;

// ===================================================================

class SimpleCarState : public ::google::protobuf::Message {
 public:
  SimpleCarState();
  virtual ~SimpleCarState();

  SimpleCarState(const SimpleCarState& from);

  inline SimpleCarState& operator=(const SimpleCarState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SimpleCarState& default_instance();

  void Swap(SimpleCarState* other);

  // implements Message ----------------------------------------------

  SimpleCarState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SimpleCarState& from);
  void MergeFrom(const SimpleCarState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ignition.msgs.Header header = 1;
  inline bool has_header() const;
  inline void clear_header();
  static const int kHeaderFieldNumber = 1;
  inline const ::ignition::msgs::Header& header() const;
  inline ::ignition::msgs::Header* mutable_header();
  inline ::ignition::msgs::Header* release_header();
  inline void set_allocated_header(::ignition::msgs::Header* header);

  // optional .ignition.msgs.Time time = 2;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 2;
  inline const ::ignition::msgs::Time& time() const;
  inline ::ignition::msgs::Time* mutable_time();
  inline ::ignition::msgs::Time* release_time();
  inline void set_allocated_time(::ignition::msgs::Time* time);

  // optional double x = 3 [default = 0];
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 3;
  inline double x() const;
  inline void set_x(double value);

  // optional double y = 4 [default = 0];
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 4;
  inline double y() const;
  inline void set_y(double value);

  // optional double heading = 5 [default = 0];
  inline bool has_heading() const;
  inline void clear_heading();
  static const int kHeadingFieldNumber = 5;
  inline double heading() const;
  inline void set_heading(double value);

  // optional double velocity = 6 [default = 0];
  inline bool has_velocity() const;
  inline void clear_velocity();
  static const int kVelocityFieldNumber = 6;
  inline double velocity() const;
  inline void set_velocity(double value);

  // @@protoc_insertion_point(class_scope:ignition.msgs.SimpleCarState)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_heading();
  inline void clear_has_heading();
  inline void set_has_velocity();
  inline void clear_has_velocity();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ignition::msgs::Header* header_;
  ::ignition::msgs::Time* time_;
  double x_;
  double y_;
  double heading_;
  double velocity_;
  friend void  protobuf_AddDesc_simple_5fcar_5fstate_2eproto();
  friend void protobuf_AssignDesc_simple_5fcar_5fstate_2eproto();
  friend void protobuf_ShutdownFile_simple_5fcar_5fstate_2eproto();

  void InitAsDefaultInstance();
  static SimpleCarState* default_instance_;
};
// ===================================================================


// ===================================================================

// SimpleCarState

// optional .ignition.msgs.Header header = 1;
inline bool SimpleCarState::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SimpleCarState::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SimpleCarState::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SimpleCarState::clear_header() {
  if (header_ != NULL) header_->::ignition::msgs::Header::Clear();
  clear_has_header();
}
inline const ::ignition::msgs::Header& SimpleCarState::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.SimpleCarState.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::ignition::msgs::Header* SimpleCarState::mutable_header() {
  set_has_header();
  if (header_ == NULL) header_ = new ::ignition::msgs::Header;
  // @@protoc_insertion_point(field_mutable:ignition.msgs.SimpleCarState.header)
  return header_;
}
inline ::ignition::msgs::Header* SimpleCarState::release_header() {
  clear_has_header();
  ::ignition::msgs::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void SimpleCarState::set_allocated_header(::ignition::msgs::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.SimpleCarState.header)
}

// optional .ignition.msgs.Time time = 2;
inline bool SimpleCarState::has_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SimpleCarState::set_has_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SimpleCarState::clear_has_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SimpleCarState::clear_time() {
  if (time_ != NULL) time_->::ignition::msgs::Time::Clear();
  clear_has_time();
}
inline const ::ignition::msgs::Time& SimpleCarState::time() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.SimpleCarState.time)
  return time_ != NULL ? *time_ : *default_instance_->time_;
}
inline ::ignition::msgs::Time* SimpleCarState::mutable_time() {
  set_has_time();
  if (time_ == NULL) time_ = new ::ignition::msgs::Time;
  // @@protoc_insertion_point(field_mutable:ignition.msgs.SimpleCarState.time)
  return time_;
}
inline ::ignition::msgs::Time* SimpleCarState::release_time() {
  clear_has_time();
  ::ignition::msgs::Time* temp = time_;
  time_ = NULL;
  return temp;
}
inline void SimpleCarState::set_allocated_time(::ignition::msgs::Time* time) {
  delete time_;
  time_ = time;
  if (time) {
    set_has_time();
  } else {
    clear_has_time();
  }
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.SimpleCarState.time)
}

// optional double x = 3 [default = 0];
inline bool SimpleCarState::has_x() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SimpleCarState::set_has_x() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SimpleCarState::clear_has_x() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SimpleCarState::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double SimpleCarState::x() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.SimpleCarState.x)
  return x_;
}
inline void SimpleCarState::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.SimpleCarState.x)
}

// optional double y = 4 [default = 0];
inline bool SimpleCarState::has_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SimpleCarState::set_has_y() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SimpleCarState::clear_has_y() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SimpleCarState::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double SimpleCarState::y() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.SimpleCarState.y)
  return y_;
}
inline void SimpleCarState::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.SimpleCarState.y)
}

// optional double heading = 5 [default = 0];
inline bool SimpleCarState::has_heading() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SimpleCarState::set_has_heading() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SimpleCarState::clear_has_heading() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SimpleCarState::clear_heading() {
  heading_ = 0;
  clear_has_heading();
}
inline double SimpleCarState::heading() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.SimpleCarState.heading)
  return heading_;
}
inline void SimpleCarState::set_heading(double value) {
  set_has_heading();
  heading_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.SimpleCarState.heading)
}

// optional double velocity = 6 [default = 0];
inline bool SimpleCarState::has_velocity() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SimpleCarState::set_has_velocity() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SimpleCarState::clear_has_velocity() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SimpleCarState::clear_velocity() {
  velocity_ = 0;
  clear_has_velocity();
}
inline double SimpleCarState::velocity() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.SimpleCarState.velocity)
  return velocity_;
}
inline void SimpleCarState::set_velocity(double value) {
  set_has_velocity();
  velocity_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.SimpleCarState.velocity)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_simple_5fcar_5fstate_2eproto__INCLUDED
