#! /bin/bash

set -e pipefail

source prereqs.lib

prereqs.init 'The Delphyne GUI source distribution prerequisites script'

prereqs.assert_sudo

if prereqs.tag_applies "default|all"; then
    prereqs.apt install --no-install-recommends libqt5multimedia5
fi

if prereqs.tag_applies "ignition|all"; then
    prereqs.install_apt_repo \
        gazebo-stable \
        http://packages.osrfoundation.org/gazebo/ubuntu-stable \
        D2486D2DD83DB69272AFE98867170598AF249743

    prereqs.apt update

    prereqs.apt install --no-install-recommends \
                libignition-common3-dev \
                libignition-math6-dev \
                libignition-msgs2-dev \
                libignition-tools-dev \
                libignition-cmake2-dev \
                libignition-cmake1-dev \
                libignition-rendering2-dev \
                libignition-gui0-dev
fi

prereqs.done
